### ISSUE TITLE
invalid memory address or nil pointer dereference. part2

### ISSUE THREAD

**Issue by perederyaev** [go-graphite/graphite-clickhouse#295]
Hi! Looks like issue described in https://github.com/go-graphite/graphite-clickhouse/issues/250 exists in current version:
```
Nov 28 18:52:18 localhost graphite-clickhouse[161601]: panic: runtime error: invalid memory address or nil pointer dereference
Nov 28 18:52:18 localhost graphite-clickhouse[161601]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1118ddf]
Nov 28 18:52:18 localhost graphite-clickhouse[161601]: goroutine 6642 [running]:
Nov 28 18:52:18 localhost graphite-clickhouse[161601]: github.com/lomik/graphite-clickhouse/render/data.(*commonStep).doneTarget(...)
Nov 28 18:52:18 localhost graphite-clickhouse[161601]:         /home/runner/work/graphite-clickhouse/graphite-clickhouse/render/data/common_step.go:26
Nov 28 18:52:18 localhost graphite-clickhouse[161601]: github.com/lomik/graphite-clickhouse/render/data.(*query).getDataPoints(0xc000260d80, {0x1981e50, 0xc0006d8150}, 0xc0001fe540)
Nov 28 18:52:18 localhost graphite-clickhouse[161601]:         /home/runner/work/graphite-clickhouse/graphite-clickhouse/render/data/query.go:143 +0x47f
Nov 28 18:52:18 localhost graphite-clickhouse[161601]: github.com/lomik/graphite-clickhouse/render/data.(*MultiTarget).Fetch.func2(0xc0005ae900?)
Nov 28 18:52:18 localhost graphite-clickhouse[161601]:         /home/runner/work/graphite-clickhouse/graphite-clickhouse/render/data/multi_target.go:206 +0x76
Nov 28 18:52:18 localhost graphite-clickhouse[161601]: created by github.com/lomik/graphite-clickhouse/render/data.(*MultiTarget).Fetch in goroutine 2206
Nov 28 18:52:18 localhost graphite-clickhouse[161601]:         /home/runner/work/graphite-clickhouse/graphite-clickhouse/render/data/multi_target.go:204 +0x63a
Nov 28 18:52:18 localhost systemd[1]: graphite-clickhouse.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

$ graphite-clickhouse --version
0.14.0

**Comment by perederyaev** [comment]
Setting "internal-aggregation = true" somehow fixes the issue.

**Comment by Hipska** [comment]
I have the exact same issue since I did a restart of the service today. Edit, seems to be #321 instead.
